CREATE DATABASE SENAI_HROADS_TARDE;
GO

USE SENAI_HROADS_TARDE;
GO

CREATE TABLE TipoUsuario(
IdTipoUsuario SMALLINT PRIMARY KEY IDENTITY(1,1),
Titulo VARCHAR(100) NOT NULL
);
GO

CREATE TABLE Usuario(
IdUsuario SMALLINT PRIMARY KEY IDENTITY(1,1),
IdTipoUsuario SMALLINT FOREIGN KEY REFERENCES TipoUsuario(idTipoUsuario),
Email VARCHAR(256) NOT NULL,
Senha VARCHAR(50) NOT NULL
);
GO

CREATE TABLE TipoHabilidade (
IdTipoHabilidade TINYINT PRIMARY KEY IDENTITY (1,1),
NomeTipo VARCHAR (10) NOT NULL
);
GO

CREATE TABLE Habilidade (
IdHabilidade TINYINT PRIMARY KEY IDENTITY (1,1),
IdTipoHabilidade TINYINT FOREIGN KEY REFERENCES TipoHabilidade(idTipoHabilidade),
NomeHabilidade VARCHAR (30) NOT NULL
);
GO

CREATE TABLE Classe (
IdClasse TINYINT PRIMARY KEY IDENTITY (1,1),
NomeClasse VARCHAR (20) NOT NULL
);
GO

CREATE TABLE Classe_Habilidade (
IdClasseHabilidade SMALLINT PRIMARY KEY IDENTITY(1,1),
IdClasse TINYINT FOREIGN KEY REFERENCES Classe(idClasse),
IdHabilidade TINYINT FOREIGN KEY REFERENCES Habilidade(idHabilidade)
);
GO

CREATE TABLE Personagem (
IdPersonagem INT PRIMARY KEY IDENTITY (1,1),
IdClasse TINYINT FOREIGN KEY REFERENCES Classe(idClasse),
NomePersonagem VARCHAR (50) NOT NULL,
VidaMax VARCHAR (2000) NOT NULL,
ManaMax VARCHAR (1200) NOT NULL,
DataCriacao DATETIME NOT NULL,
DataAtualizacao DATETIME NOT NULL
);